# Day 1: Introduction to Data Engineering

**Pandas** - Pandas is a Python library that helps us work with tables of data.

**Series** = One Column

**DataFrame** = Complete Table

> 1. Read files

In [117]:
import pandas as pd                                       # import pandas into notebook as pd(a name)
df = pd.read_csv("/content/student_performance.csv")      # load csv and store it inside dataframe(df)



> 2. View data

In [118]:
df.head(10)    # show first 10 rows

,student_id,name,age,gender,department,semester,math_score,science_score,english_score,programming_score,attendance_percentage,city,admission_year
0,1001,Aarav Sharma,19,Male,Computer Science,2,85,78,72,91,92,Mumbai,2023
1,1002,Priya Patel,20,Female,Computer Science,2,76,82,88,79,87,Ahmedabad,2023
2,1003,Rohit Verma,19,Male,Electronics,2,65,74,61,55,78,Delhi,2023
3,1004,Sneha Reddy,20,Female,Mechanical,2,70,80,75,48,95,Hyderabad,2023
4,1005,Arjun Nair,19,Male,Computer Science,2,92,88,81,95,90,Kochi,2023
5,1006,Meera Joshi,20,Female,Electronics,2,58,66,70,52,72,Pune,2023
6,1007,Kiran Kumar,21,Male,Civil,2,73,69,65,40,85,Bangalore,2023
7,1008,Divya Singh,19,Female,Computer Science,2,88,91,84,93,96,Lucknow,2023
8,1009,Rahul Mishra,20,Male,Mechanical,2,62,71,58,45,68,Varanasi,2023
9,1010,Ananya Das,19,Female,Computer Science,2,95,89,90,97,98,Kolkata,2023

In [119]:
df.tail()    # show last 5 rows

,student_id,name,age,gender,department,semester,math_score,science_score,english_score,programming_score,attendance_percentage,city,admission_year
25,1026,Rekha Nair,20,Female,Electronics,2,72,77,73,63,82,Kochi,2023
26,1027,Gaurav Shukla,21,Male,Computer Science,2,84,79,75,87,87,Lucknow,2023
27,1028,Sunita Pillai,19,Female,Civil,2,60,65,68,39,73,Thiruvananthapuram,2023
28,1029,Nitin Jain,20,Male,Mechanical,2,75,76,70,50,84,Indore,2023
29,1030,Akanksha Yadav,19,Female,Computer Science,2,91,93,87,94,95,Agra,2023

In [120]:
df.info()      # information of the columns (count of non-null values, and datatypes)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 13 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   student_id             30 non-null     int64
 1   name                   30 non-null     object
 2   age                    30 non-null     int64
 3   gender                 30 non-null     object
 4   department             30 non-null     object
 5   semester               30 non-null     int64
 6   math_score             30 non-null     int64
 7   science_score          30 non-null     int64
 8   english_score          30 non-null     int64
 9   programming_score      30 non-null     int64
 10  attendance_percentage  30 non-null     int64
 11  city                   30 non-null     object
 12  admission_year         30 non-null     int64
dtypes: int64(9), object(4)
memory usage: 3.2+ KB

In [121]:
df.describe()     # statistical summary of each columns

,student_id,age,semester,math_score,science_score,english_score,programming_score,attendance_percentage,admission_year
count,30.000000,30.000000,30.0,30.000000,30.000000,30.000000,30.000000,30.000000,30.0
mean,1015.500000,19.733333,2.0,76.066667,77.833333,74.166667,67.600000,84.500000,2023.0
std,8.803408,0.739680,0.0,11.467896,8.554423,10.003735,21.041175,9.379913,0.0
min,1001.000000,19.000000,2.0,56.000000,61.000000,55.000000,38.000000,65.000000,2023.0
25%,1008.250000,19.000000,2.0,67.250000,71.250000,67.250000,49.250000,77.250000,2023.0
50%,1015.500000,20.000000,2.0,75.500000,78.000000,75.000000,66.000000,86.500000,2023.0
75%,1022.750000,20.000000,2.0,85.750000,83.750000,81.750000,88.750000,91.750000,2023.0
max,1030.000000,21.000000,2.0,95.000000,93.000000,90.000000,97.000000,98.000000,2023.0

In [122]:
print(f'Rows and columns:{df.shape}')     # 0-> rows
print(f'Rows   : {df.shape[0]}')          # 1-> columns
print(f'Columns: {df.shape[1]}')

Rows and columns:(30, 13)
Rows   : 30
Columns: 13

In [123]:
df.dtypes   # The datatype of each column.

student_id                int64
name                     object
age                       int64
gender                   object
department               object
semester                  int64
math_score                int64
science_score             int64
english_score             int64
programming_score         int64
attendance_percentage     int64
city                     object
admission_year            int64
dtype: object

In [124]:
print(df.columns.tolist())  # prints all column names as a Python list.

['student_id', 'name', 'age', 'gender', 'department', 'semester', 'math_score', 'science_score', 'english_score', 'programming_score', 'attendance_percentage', 'city', 'admission_year']



> 3. Handle Missing Values

In [125]:
df.isnull().sum()   # How many missing values are present in each column
                    # isnull()-> Checks whether values are empty or missing.
                    # sum()-> Counts the True values.

student_id               0
name                     0
age                      0
gender                   0
department               0
semester                 0
math_score               0
science_score            0
english_score            0
programming_score        0
attendance_percentage    0
city                     0
admission_year           0
dtype: int64

****



> 4. Select Columns

In [126]:
df['admission_year']

0     2023
1     2023
2     2023
3     2023
4     2023
5     2023
6     2023
7     2023
8     2023
9     2023
10    2023
11    2023
12    2023
13    2023
14    2023
15    2023
16    2023
17    2023
18    2023
19    2023
20    2023
21    2023
22    2023
23    2023
24    2023
25    2023
26    2023
27    2023
28    2023
29    2023
Name: admission_year, dtype: int64

In [127]:
df[['admission_year','student_id']]

    admission_year  student_id
0             2023        1001
1             2023        1002
2             2023        1003
3             2023        1004
4             2023        1005
5             2023        1006
6             2023        1007
7             2023        1008
8             2023        1009
9             2023        1010
10            2023        1011
11            2023        1012
12            2023        1013
13            2023        1014
14            2023        1015
15            2023        1016
16            2023        1017
17            2023        1018
18            2023        1019
19            2023        1020
20            2023        1021
21            2023        1022
22            2023        1023
23            2023        1024
24            2023        1025
25            2023        1026
26            2023        1027
27            2023        1028
28            2023        1029
29            2023        1030

In [128]:
print(df["department"].unique())    # removes repeated values and shows unique values
print(df["admission_year"].unique())

['Computer Science' 'Electronics' 'Mechanical' 'Civil']
[2023]



> 5. Filtering Rows

In [129]:
cs_students = df[df["department"]=="Computer Science"]   # select students from the "Computer Science" department
high_attendance = df[df["attendance_percentage"] > 90]   # filters where attendance is above 90

 ****

> 6. Creating a new column

In [130]:
df['total_score']=df['math_score']+df['english_score']+df['programming_score']+df['science_score']   # adding all score to get total score

In [131]:
# Finds the student with the highest total score and stores that row in top_student.

top_student = df.loc[df['total_score'].idxmax()]     # df.loc[]  ->  Used to select a row using index label.
print(top_student)                                   # .idxmax() ->  Finds the index (row number) of the highest value.

student_id                           1010
name                           Ananya Das
age                                    19
gender                             Female
department               Computer Science
semester                                2
math_score                             95
science_score                          89
english_score                          90
programming_score                      97
attendance_percentage                  98
city                              Kolkata
admission_year                       2023
total_score                           371
Name: 9, dtype: object



> 7. Grouping and Aggregation.

In [132]:
dept_avg = df.groupby('department')['total_score'].mean().round(2)   # Average of total_score for each department
print(dept_avg)

department
Civil               235.80
Computer Science    340.15
Electronics         277.50
Mechanical          267.33
Name: total_score, dtype: float64



> 8. Sort Data

In [133]:
df_sorted = df.sort_values(by='total_score',ascending=False)
print("="*50)
print("        Top 10 Students by total score:")
print("="*50)
print(df_sorted[['name','department','total_score']].head(10))

==================================================
        Top 10 Students by total score:
==================================================
              name        department  total_score
9       Ananya Das  Computer Science          371
21     Tanvi Mehta  Computer Science          367
29  Akanksha Yadav  Computer Science          365
4       Arjun Nair  Computer Science          356
7      Divya Singh  Computer Science          356
17  Swati Kulkarni  Computer Science          354
24       Amit Bose  Computer Science          336
12      Suresh Rao  Computer Science          334
19    Nisha Kapoor  Computer Science          327
0     Aarav Sharma  Computer Science          326

# Practice Questions

In [134]:
""" Question 1:
How many students are from the Electronics department?"""

students_in_ec = df[df["department"]=="Electronics"]
print("Total Number of Students in Electronics:")
print(len(students_in_ec))

Total Number of Students in Electronics:
6

In [135]:
""" Question 2:
What is the average attendance of female students?"""

female_students = df[df['gender']=="Female"]
print("Average attendance of female students:")
avg_attendance = female_students["attendance_percentage"].mean()
print(avg_attendance)

Average attendance of female students:
88.53333333333333

In [136]:
""" Question 3:
Who is the student with the lowest programming score?"""

df_sort_prog_score = df.sort_values(by="programming_score",ascending= True)
print("The student with the lowest programming score")
print(df_sort_prog_score['name'].head(1))

The student with the lowest programming score
16    Manoj Pandey
Name: name, dtype: object

In [137]:
"""Question 4:
How many students scored above 80 in math?"""

df_math_score = df[df["math_score"]>80]
print("Students scored above 80 in math")
print(len(df_math_score))

Students scored above 80 in math
11

In [138]:
""" Question 5:
What is the average total_score for students with attendance above 90%?"""

attendance_above_90 = df[df["attendance_percentage"]>90]
print("The average total_score for students with attendance above 90%")
print(attendance_above_90["total_score"].mean())

The average total_score for students with attendance above 90%
335.8

# Student Data Explorer -MINI PROJECT 1

## Objective
Analyze student performance data using Pandas and generate key insights.

## Dataset Columns
- name
- gender
- department
- math_score
- programming_score
- attendance_percentage
- total_score

## Tasks

### 1. Dataset Overview
- Total students
- Total columns
- Unique departments

### 2. Department Analysis
- Student count by department

### 3. Score Analysis
- Highest, lowest, and average math score
- Average programming score
- Average attendance

### 4. Gender Analysis
- Average total score by gender

### 5. Top Performers
- Top 5 students by total score

### 6. Attendance Analysis
- Students with attendance below 75%

Coding:

In [139]:

print("="*60)
print("                  Student Data Explorer                                           ")
print("="*60)
print("[1] Dataset Objective:\n---------------------------------------------")
print("Total Number of students: ",df.shape[0])
print("Total Number of columns: ",df.shape[1])
print("Total Number of unique departments: ",len(df["department"].unique()))
print(df['department'].unique(),"\n")
print("[2] Department-wise Analysis:\n---------------------------------------------")
print("The count of students in each department:\n",df['department'].value_counts(),"\n")

print("[3] Score Analysis:\n---------------------------------------------")
 # Highest math score
print("The Highest math score:",df["math_score"].max())

# Lowest math score
print("The Lowest math score:",df["math_score"].min())

# Average math score
print("The Average math score:",df["math_score"].mean().round(2))

# Average Programming score
print("The Average Programming score:",df["programming_score"].mean().round(2))

# Average attendance percentage
print("The Average attendance percentage:",df["attendance_percentage"].mean().round(2),"\n")

print("[4] Gender wise Analysis:\n---------------------------------------------")
# Average total score grouped by gender
total_score_by_gender = df.groupby('gender')['total_score'].mean().round(2)
print("The Average total score grouped by gender:\n",total_score_by_gender,"\n")
print("[5] Top performers:\n---------------------------------------------")
# The top 5 students based on total_Score.
top_5_students = df.sort_values(by='total_score',ascending=False).head(5)
print("The Top 5 students based on total_Score:\n",top_5_students[['name','department','total_score']],"\n")

print("[6] Attendance Analysis:\n---------------------------------------------")
# Students whose attendance is below 75%
stud_below_75 = df[df['attendance_percentage']<75]
if len(stud_below_75)>0:
  print("The Students whose attendance is below 75%:\n",stud_below_75[['name','department','total_score','attendance_percentage']])
else:
  print("All students have attendance above 75%")

============================================================
                  Student Data Explorer
============================================================
[1] Dataset Objective:
---------------------------------------------
Total Number of students:  30
Total Number of columns:  14
Total Number of unique departments:  4
['Computer Science' 'Electronics' 'Mechanical' 'Civil']

[2] Department-wise Analysis:
---------------------------------------------
The count of students in each department:
 department
Computer Science    13
Electronics          6
Mechanical           6
Civil                5
Name: count, dtype: int64

[3] Score Analysis:
---------------------------------------------
The Highest math score: 95
The Lowest math score: 56
The Average math score: 76.07
The Average Programming score: 67.6
The Average attendance percentage: 84.5

[4] Gender wise Analysis:
---------------------------------------------
The Average total score grouped by gender:
 gender
Female    310.67
Male      280.67
Name: total_score, dtype: float64

[5] Top performers:
---------------------------------------------
The Top 5 students based on total_Score:
               name        department  total_score
9       Ananya Das  Computer Science          371
21     Tanvi Mehta  Computer Science          367
29  Akanksha Yadav  Computer Science          365
4       Arjun Nair  Computer Science          356
7      Divya Singh  Computer Science          356

[6] Attendance Analysis:
---------------------------------------------
The Students whose attendance is below 75%:
              name   department  total_score  attendance_percentage
5     Meera Joshi  Electronics          246                     72
8    Rahul Mishra   Mechanical          236                     68
16   Manoj Pandey        Civil          210                     65
20  Harish Pillai  Electronics          259                     74
22   Sanjay Dubey        Civil          228                     70
27  Sunita Pillai        Civil          232                     73

--END OF MINIPROJECT DAY-1--